# Generated by Django 5.1.5 on 2025-01-20 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentportfolioasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investmentasset'),
        ),
        migrations.AddField(
            model_name='investmentportfolioasset',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investmentportfolio'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.investmentasset'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='investmentportfolioasset',
            unique_together={('portfolio', 'asset')},
        ),
    ]
