# Generated by Django 5.1.5 on 2025-02-17 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.TextField(choices=[('FOOD', 'Food & Restaurants'), ('BILLS', 'Bills & Utilities'), ('TRANSPORT', 'Transportation'), ('SHOPPING', 'Shopping & Entertainment'), ('HEALTH', 'Health & Beauty'), ('EDUCATION', 'Education & Development'), ('SAVINGS', 'Savings & Investments'), ('OTHER', 'Other/Unexpected Expenses')], default='OTHER', max_length=15),
        ),
    ]
