# Generated by Django 5.1.5 on 2025-01-28 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
    ]
